version: '3'
services:
  jenkins:
    image: "jenkins:2.60.1-alpine"
    ports:
    - "8081:8080"
    volumes:
    - "./jenkins-data:/var/jenkins_home"
    environment:
    - http_proxy=$http_proxy
    - https_proxy=$https_proxy
    - ftp_proxy=$ftp_proxy
    - no_proxy=$no_proxy
    - HTTP_PROXY=$http_proxy
    - HTTPS_PROXY=$https_proxy
    - FTP_PROXY=$ftp_proxy
    - NO_PROXY=$no_proxy
