version: '3'
services:
  jenkins:
    image: "jenkins:2.60.1-alpine"
    ports:
    - "8081:8080"
    volumes:
    - ./jenkins-data/config.xml:/var/jenkins_home/config.xml
    - ./jenkins-data/jenkins.install.InstallUtil.lastExecVersion:/var/jenkins_home/jenkins.install.InstallUtil.lastExecVersion
    - ./jenkins-data/jobs:/var/jenkins_home/jobs
    - ./jenkins-data/proxy.xml:/var/jenkins_home/proxy.xml
    - ./jenkins-data/users:/var/jenkins_home/users
    - ./jenkins-data/jenkins.plugins.slack.SlackNotifier.xml:/var/jenkins_home/jenkins.plugins.slack.SlackNotifier.xml
    environment:
    - http_proxy=$http_proxy
    - https_proxy=$https_proxy
    - ftp_proxy=$ftp_proxy
    - no_proxy=$no_proxy
    - HTTP_PROXY=$http_proxy
    - HTTPS_PROXY=$https_proxy
    - FTP_PROXY=$ftp_proxy
    - NO_PROXY=$no_proxy
